---
# tasks file for ./roles/collectd


- name: Install tasks
  block:
    - name: Include packages installation tasks
      ansible.builtin.include_tasks: packages.yml

    - name: Include collectd Prometheus configuration tasks
      ansible.builtin.include_tasks: prometheus.yml

    - name: Include collectd status check tasks
      ansible.builtin.include_tasks: ensure_collectd_state.yml
  when: collectd_action == 'install'

- name: Removal tasks
  block:
    - name: Include collectd removal tasks
      ansible.builtin.include_tasks: remove_collectd.yml
  when: collectd_action == 'remove'

