---

- name: Install collectd and plugins
  ansible.builtin.package:
    name:
      - collectd
      - collectd-core
    state: latest
  register: package_status
  become: yes
  notify: restart_collectd
  changed_when: package_status is changed

