---
# defaults file for ./roles/collectd

collectd_prometheus_port: 9103
collectd_action: 'install'
collectd_plugin_list:
  - df
  - processes
  - protocols
  - swap
  - tcpconns
  - uptime
  - users
  - vmem

