---

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - lsof
    - mc
    - nano
    - tar
    - unzip
    - vim
    - zip
  when: install_packages
  become: yes

