- name: Gather network interfaces of managed nodes
  hosts: managed_nodes
  gather_facts: false
  tasks:
    - name: Get interfaces
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'
          - 'network'
      register: net_info

    - name: Print interfaces
      debug:
        var: net_info.ansible_facts.ansible_interfaces

